### ISSUE TITLE
TUIO Support

### ISSUE THREAD

**Issue by abhishekshrimali** [richardeakin/Cinder-View#14]
Hi Richard,

I am working on cinder view and found it very helpful to create UI.

I have to use TUIO with default 3333 port support. After changing windows touch to TUIO controls touch events are not working.

Is there anyway to integrate TUIO with cinder view. Please help.

Thanks,
Abhishek Shrimali

**Comment by richardeakin** [comment]
Hm, not sure, don't have much experience with TUIO myself so don't know what that would entail exactly. Can you get by with creating `ci::app::TouchEvent`s from what you get from TUIO, and then inject those into your `ui::Graph`? You can see how I injected test touches in the test suite [here](https://github.com/richardeakin/Cinder-View/blob/f4b966291e9e66eda72943d6a37c497e21533df3/test/src/MultiTouchTest.cpp#L253-L313).

**Comment by abhishekshrimali** [comment]
Hey Richard,
Thanks a lot. I was working on some other stuff and just started working on it. I got one solution to this. 

I have enabled TUIO in my main App file and its working with TUIO.

Below is the code 
// Bind the Osc Receiver...
	try {
		mOscReceiver.bind();
	}
	catch (const ci::Exception &ex) {
		CI_LOG_EXCEPTION("OscReceiver bind", ex);
		quit();
	}
	// And listen for messages.
	mOscReceiver.listen(
		[](asio::error_code ec, asio::ip::udp::endpoint ep) -> bool {
		if (ec) {
			CI_LOG_E("Error on listener: " << ec.message() << " Error Value: " << ec.value());
			return false;
		}
		else
			return true;
	});

and its initialized with below parameters
 :App(), mOscReceiver(tuio::Receiver::DEFAULT_TUIO_PORT),
	mTuio(app::getWindow(), &mOscReceiver)
