### ISSUE TITLE
More than one Graph Elements

### ISSUE THREAD

**Issue by abhishekshrimali** [richardeakin/Cinder-View#19]
Hi Richard,

Thanks for your reply on my previous issue. I need your help for one more issue.

I have two graph objects with different subviews. All the subviews has their touch events and its working fine.But the places where rendered graph elements overlaps, touch events works only for first rendered graph object. events are not working for any other graph object rendered on this object.

Is there a way to stack graph objects and set the priority based on their rendering order.

Kindly Help.

Thanks,
Abhishek Shrimali

**Comment by richardeakin** [comment]
Not sure yet what problem you're seeing, although I can verify that touch events works with multiple Graphs as this is how I currently use it. Things to try:

- Try changing the [priority](https://github.com/richardeakin/Cinder-View/blob/6fda95cf8216fa49bbef2496bc0c80474dbac082/src/ui/Graph.h#L75) on `Graph::EventOptions`, which you pass in to [connectEvents](https://github.com/richardeakin/Cinder-View/blob/6fda95cf8216fa49bbef2496bc0c80474dbac082/src/ui/Graph.h#L87).
- Make sure you mark whatever touches are handled by the first receiver, as done [here](https://github.com/richardeakin/Cinder-View/blob/6fda95cf8216fa49bbef2496bc0c80474dbac082/test/src/MultiTouchTest.cpp#L39-L40). You also need to return true if _any_ touches within the event are handled.

Sorry for the lack of documentation on this. It is our first approach to supporting multi-touch and so we are awaiting more user testing and feedback before deciding if it is the correct way to go for v1. Keep me updated!

**Comment by abhishekshrimali** [comment]
Hey Richard,

Thanks a lot, I followed steps provided by you and its working fine :)
