### ISSUE TITLE
Cant build tests OSX.

### ISSUE THREAD

**Issue by felixfaire** [richardeakin/Cinder-View#22]
Hi Rich, this might just be my novice CMake abilities but i've beed unable to run the latest test views from source.

Opening the xcode project fails returning:
`Cinder/blocks/Cinder-View/xcode/cinder-view.xcodeproj cannot be opened because it is missing its project.pbxproj file.`

Building with CMake fails returning:

```
...
...
[ 85%] Building CXX object test/proj/cmake/CMakeFiles/ViewTests.dir/__/__/src/LayoutTests.cpp.o
[ 88%] Building CXX object test/proj/cmake/CMakeFiles/ViewTests.dir/__/__/src/MultiTouchTest.cpp.o
[ 92%] Building CXX object test/proj/cmake/CMakeFiles/ViewTests.dir/__/__/src/ScrollTests.cpp.o
make[2]: *** No rule to make target `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/Cocoa.framework', needed by `Debug/ViewTests/ViewTests.app/Contents/MacOS/ViewTests'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[ 96%] Building CXX object test/proj/cmake/CMakeFiles/ViewTests.dir/__/__/src/ViewTestsApp.cpp.o
make[1]: *** [test/proj/cmake/CMakeFiles/ViewTests.dir/all] Error 2
make: *** [all] Error 2
```

Am i missing something basic here? I'd love to check this out.

**Comment by felixfaire** [comment]
Just realised the xcode project in the tests/proj folder works as expected. Are the other two xcode folders:

```
/xcode
/tests/xcode
```

necessary?

**Comment by richardeakin** [comment]
Whoops, was going through emails and only saw this now.  I think those two folders might be from an older version? These are the two important ones:

```
https://github.com/richardeakin/Cinder-View/tree/master/proj/xcode/cinder-view.xcodeproj
https://github.com/richardeakin/Cinder-View/tree/master/test/proj/xcode/ViewTests.xcodeproj
```

Although they might need a couple minor updates for file changes / newer versions of Xcode. I do believe I updated the cmake stuff not that long ago.
